{%set build = 0 %}
{%set version = '2016.1' %}

package:
  name: pycuda
  version: {{version}}

about:
  home: http://mathema.tician.de/software/pycuda
  license: MIT License
  summary: "Python wrapper for NVIDIA CUDA."

source:
  fn: pycuda-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/p/pycuda/pycuda-{{version}}.tar.gz
  md5: 96e50fd4b079d4f6e8bd1bd2207ca48d

requirements:
  build:
    - decorator >=3.2.0
    - numpy
    - pytest >=2
    - python
    - pytools >=2011.2
    - setuptools

  run:
    - decorator >=3.2.0
    - numpy
    - python
    - pytools >=2011.2

build:
  number: {{build}}
  string: np{{np}}py{{py}}_cuda75_{{build}}
  preserve_egg_dir: yes
  script:
    - python configure.py --cuda-root=/usr/local/cuda/
    - python setup.py install
